#!/bin/sh
APPDIR=`dirname $0`;
java -XstartOnFirstThread -cp "$APPDIR/src:$APPDIR/bin:/Developer/Java/gwt-mac-1.4.61/gwt-user.jar:/Developer/Java/gwt-mac-1.4.61/gwt-dev-mac.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/www" "$@" org.pentaho.halogen.Halogen/Halogen.html;
